services:
  auth_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  room_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - room_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d room_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  booking_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - booking_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth_service:
    build:
      context: .
      target: auth-service
    image: kirillvolostnov/auth_service:latest
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DEFAULT_USERNAME: ${DEFAULT_USERNAME}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}

  room_service:
    build:
      context: .
      target: room-service
    image: kirillvolostnov/room_service:latest
    depends_on:
      room_db:
        condition: service_healthy
    environment:
      ROOM_DATABASE_URL: ${ROOM_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}

  booking_service:
    build:
      context: .
      target: booking-service
    image: kirillvolostnov/booking_service:latest
    depends_on:
      booking_db:
        condition: service_healthy
    environment:
      BOOKING_DATABASE_URL: ${BOOKING_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}

  frontend:
    build:
      context: .
      target: frontend
    image: kirillvolostnov/frontend:latest
    depends_on:
      - auth_service
      - room_service
      - booking_service

  gateway:
    build:
      context: .
      target: gateway
    image: kirillvolostnov/gateway:latest
    depends_on:
      - frontend
      - auth_service
      - room_service
      - booking_service
    ports:
      - "80:80"

volumes:
  auth_pg_data:
  room_pg_data:
  booking_pg_data:
